import React from 'react';
import type { Metadata } from 'next';
import '@/styles/global.scss';
import { getLocale } from 'next-intl/server';
import { ColorSchemeScript } from '@mantine/core';
import { getManagersPersistentStateFromCookies } from '@/managers/utils';
import ManagersRegistry from '@/managers/ManagersRegistry';
import { THEME_COLOR_SCHEMA_STORE_NAME } from '@/managers/ThemeManager/def';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const managersPersistentState = await getManagersPersistentStateFromCookies();

  return (
    <html lang={locale} dir={managersPersistentState.theme.direction} suppressHydrationWarning>
      <head>
        <ColorSchemeScript
          defaultColorScheme={managersPersistentState.theme.colorScheme}
          localStorageKey={THEME_COLOR_SCHEMA_STORE_NAME}
        />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no" />
      </head>
      <body className="antialiased" suppressHydrationWarning={false}>
        <ManagersRegistry persistentState={managersPersistentState}>{children}</ManagersRegistry>
      </body>
    </html>
  );
}
